/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-asa-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.asa.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-asa-stats.yang */
public class tailfNedCiscoAsaStats extends ConfNamespace {
    public static final int hash = 1570711820;
    public int hash() {
        return tailfNedCiscoAsaStats.hash;
    }

    public static final String id = "http://cisco.com/ned/asa-stats";
    public String id() {
        return tailfNedCiscoAsaStats.id;
    }

    public static final String uri = "http://cisco.com/ned/asa-stats";
    public String uri() {
        return tailfNedCiscoAsaStats.uri;
    }

    public static final String prefix = "asa-stats";
    public String prefix() {
        return tailfNedCiscoAsaStats.prefix;
    }

    public tailfNedCiscoAsaStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _inactivity = 1503490564;
    public static final String _inactivity_ = "inactivity";
    public static final int    _vpn_sessiondb = 1663929639;
    public static final String _vpn_sessiondb_ = "vpn-sessiondb";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _any = 383440309;
    public static final String _any_ = "any";
    public static final int    _login_time = 56217328;
    public static final String _login_time_ = "login-time";
    public static final int    _tx_bytes = 391747870;
    public static final String _tx_bytes_ = "tx-bytes";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _license = 1917123854;
    public static final String _license_ = "license";
    public static final int    _duration = 686902226;
    public static final String _duration_ = "duration";
    public static final int    _args = 578380655;
    public static final String _args_ = "args";
    public static final int    _output_bytes = 741596694;
    public static final String _output_bytes_ = "output-bytes";
    public static final int    _line_protocol_status = 1922981495;
    public static final String _line_protocol_status_ = "line-protocol-status";
    public static final int    _exec = 1716494663;
    public static final String _exec_ = "exec";
    public static final int    _context = 1600175075;
    public static final String _context_ = "context";
    public static final int    _post_encrypt_octets = 1050338138;
    public static final String _post_encrypt_octets_ = "post-encrypt-octets";
    public static final int    _output_rate = 415725935;
    public static final String _output_rate_ = "output-rate";
    public static final int    _inside_interface = 1475084082;
    public static final String _inside_interface_ = "inside-interface";
    public static final int    _post_decrypt_octets = 41157005;
    public static final String _post_decrypt_octets_ = "post-decrypt-octets";
    public static final int    _input_bytes = 70371030;
    public static final String _input_bytes_ = "input-bytes";
    public static final int    _ssl = 979553486;
    public static final String _ssl_ = "ssl";
    public static final int    _anyconnect = 586554715;
    public static final String _anyconnect_ = "anyconnect";
    public static final int    _rx_bytes = 2068252239;
    public static final String _rx_bytes_ = "rx-bytes";
    public static final int    _input_rate = 455904625;
    public static final String _input_rate_ = "input-rate";
    public static final int    _show = 1568086057;
    public static final String _show_ = "show";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _clear = 634788371;
    public static final String _clear_ = "clear";
}
