/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-asa-meta.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.asa.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-asa-meta.yang */
public class tailfNedCiscoAsaMeta extends ConfNamespace {
    public static final int hash = 1966825295;
    public int hash() {
        return tailfNedCiscoAsaMeta.hash;
    }

    public static final String id = "http://cisco.com/ned/asa-meta";
    public String id() {
        return tailfNedCiscoAsaMeta.id;
    }

    public static final String uri = "http://cisco.com/ned/asa-meta";
    public String uri() {
        return tailfNedCiscoAsaMeta.uri;
    }

    public static final String prefix = "asa-meta";
    public String prefix() {
        return tailfNedCiscoAsaMeta.prefix;
    }

    public tailfNedCiscoAsaMeta() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _context_config_url_file_delete = 2010445992;
    public static final String _context_config_url_file_delete_ = "context-config-url-file-delete";
    public static final int    _cisco_asa_context_name = 1013158337;
    public static final String _cisco_asa_context_name_ = "cisco-asa-context-name";
    public static final int    _admin_device = 1908708441;
    public static final String _admin_device_ = "admin-device";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _number_of_retries = 1188193865;
    public static final String _number_of_retries_ = "number-of-retries";
    public static final int    _cisco_asa_write_memory_setting = 171195286;
    public static final String _cisco_asa_write_memory_setting_ = "cisco-asa-write-memory-setting";
    public static final int    _get_device_config_settings = 908137148;
    public static final String _get_device_config_settings_ = "get-device-config-settings";
    public static final int    _cisco_asa_log_verbose = 130345172;
    public static final String _cisco_asa_log_verbose_ = "cisco-asa-log-verbose";
    public static final int    _time_between_retry = 124382029;
    public static final String _time_between_retry_ = "time-between-retry";
    public static final int    _extended_parser = 82876680;
    public static final String _extended_parser_ = "extended-parser";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _cisco_asa_transaction_id_method = 524531175;
    public static final String _cisco_asa_transaction_id_method_ = "cisco-asa-transaction-id-method";
    public static final int    _cisco_asa_context_list = 1262927033;
    public static final String _cisco_asa_context_list_ = "cisco-asa-context-list";
    public static final int    _question = 1260341232;
    public static final String _question_ = "question";
    public static final int    _cisco_asa = 1917820038;
    public static final String _cisco_asa_ = "cisco-asa";
    public static final int    _auto = 1146214388;
    public static final String _auto_ = "auto";
    public static final int    _cisco_asa_auto_prompts = 431399049;
    public static final String _cisco_asa_auto_prompts_ = "cisco-asa-auto-prompts";
    public static final int    _use_startup_config = 1295144404;
    public static final String _use_startup_config_ = "use-startup-config";
    public static final int    _method = 781988118;
    public static final String _method_ = "method";
    public static final int    _answer = 638178487;
    public static final String _answer_ = "answer";
}
