/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-asa-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.asa.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-asa-oper.yang */
public class tailfNedCiscoAsaOper extends ConfNamespace {
    public static final int hash = 1989390194;
    public int hash() {
        return tailfNedCiscoAsaOper.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-asa/oper";
    public String id() {
        return tailfNedCiscoAsaOper.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-asa/oper";
    public String uri() {
        return tailfNedCiscoAsaOper.uri;
    }

    public static final String prefix = "asa-op";
    public String prefix() {
        return tailfNedCiscoAsaOper.prefix;
    }

    public tailfNedCiscoAsaOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _encrypted = 1422131983;
    public static final String _encrypted_ = "encrypted";
    public static final int    _regexp = 1858481280;
    public static final String _regexp_ = "regexp";
    public static final int    _cisco_asa_oper = 1191556428;
    public static final String _cisco_asa_oper_ = "cisco-asa-oper";
    public static final int    _cleartext = 140716928;
    public static final String _cleartext_ = "cleartext";
    public static final int    _secrets = 1439464346;
    public static final String _secrets_ = "secrets";
}
