/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-asa-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.asa.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-asa-id.yang */
public class tailfNedCiscoAsaId extends ConfNamespace {
    public static final int hash = 530219739;
    public int hash() {
        return tailfNedCiscoAsaId.hash;
    }

    public static final String id = "http://cisco.com/ned/asa-id";
    public String id() {
        return tailfNedCiscoAsaId.id;
    }

    public static final String uri = "http://cisco.com/ned/asa-id";
    public String uri() {
        return tailfNedCiscoAsaId.uri;
    }

    public static final String prefix = "asa-id";
    public String prefix() {
        return tailfNedCiscoAsaId.prefix;
    }

    public tailfNedCiscoAsaId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_asa = 1917820038;
    public static final String _cisco_asa_ = "cisco-asa";
}
