/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/example-serial.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.examples.router.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module example-serial.yang */
public class exampleSerial extends ConfNamespace {
    public static final int hash = 1579684977;
    public int hash() {
        return exampleSerial.hash;
    }

    public static final String id = "http://example.com/example-serial";
    public String id() {
        return exampleSerial.id;
    }

    public static final String uri = "http://example.com/example-serial";
    public String uri() {
        return exampleSerial.uri;
    }

    public static final String prefix = "ex";
    public String prefix() {
        return exampleSerial.prefix;
    }

    public exampleSerial() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ipcp = 480124781;
    public static final String _ipcp_ = "ipcp";
    public static final int    _group = 1540685982;
    public static final String _group_ = "group";
    public static final int    _minimum = 205690348;
    public static final String _minimum_ = "minimum";
    public static final int    _dns = 577671700;
    public static final String _dns_ = "dns";
    public static final int    _additional_delay_value = 162813971;
    public static final String _additional_delay_value_ = "additional-delay-value";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _one_time = 1099783556;
    public static final String _one_time_ = "one-time";
    public static final int    _mandatory = 1842133828;
    public static final String _mandatory_ = "mandatory";
    public static final int    _list_name = 388687281;
    public static final String _list_name_ = "list-name";
    public static final int    _serial = 570166199;
    public static final String _serial_ = "serial";
    public static final int    _minimum_value = 1510487130;
    public static final String _minimum_value_ = "minimum-value";
    public static final int    _ppp = 1973857664;
    public static final String _ppp_ = "ppp";
    public static final int    _multilink = 1890437206;
    public static final String _multilink_ = "multilink";
    public static final int    _authentication = 838318934;
    public static final String _authentication_ = "authentication";
    public static final int    _links = 159989304;
    public static final String _links_ = "links";
    public static final int    _primary = 1409818743;
    public static final String _primary_ = "primary";
    public static final int    _delay_value = 1537712187;
    public static final String _delay_value_ = "delay-value";
    public static final int    _authorization = 1275762932;
    public static final String _authorization_ = "authorization";
    public static final int    _method = 781988118;
    public static final String _method_ = "method";
    public static final int    _optional = 321395874;
    public static final String _optional_ = "optional";
    public static final int    _fragment = 587894344;
    public static final String _fragment_ = "fragment";
    public static final int    _delay = 200515694;
    public static final String _delay_ = "delay";
    public static final int    _accounting = 803748480;
    public static final String _accounting_ = "accounting";
}
