/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/router.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.examples.router.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module router.yang */
public class router extends ConfNamespace {
    public static final int hash = 1703081446;
    public int hash() {
        return router.hash;
    }

    public static final String id = "http://example.com/router";
    public String id() {
        return router.id;
    }

    public static final String uri = "http://example.com/router";
    public String uri() {
        return router.uri;
    }

    public static final String prefix = "r";
    public String prefix() {
        return router.prefix;
    }

    public router() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ndots = 1020069729;
    public static final String _ndots_ = "ndots";
    public static final int    _transmit = 1705430781;
    public static final String _transmit_ = "transmit";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _jitter = 965990611;
    public static final String _jitter_ = "jitter";
    public static final int    _administrator = 742532166;
    public static final String _administrator_ = "administrator";
    public static final int    _trusted = 17999496;
    public static final String _trusted_ = "trusted";
    public static final int    _restrict = 182285917;
    public static final String _restrict_ = "restrict";
    public static final int    _receive = 716682309;
    public static final String _receive_ = "receive";
    public static final int    _duplex = 1052737030;
    public static final String _duplex_ = "duplex";
    public static final int    _dns = 577671700;
    public static final String _dns_ = "dns";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _iburst = 1462625859;
    public static final String _iburst_ = "iburst";
    public static final int    _speed = 1423237997;
    public static final String _speed_ = "speed";
    public static final int    _route = 2058743578;
    public static final String _route_ = "route";
    public static final int    _next_hop = 1889650088;
    public static final String _next_hop_ = "next-hop";
    public static final int    _ntp = 2125290123;
    public static final String _ntp_ = "ntp";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _syslog = 1431433453;
    public static final String _syslog_ = "syslog";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _attempts = 494356450;
    public static final String _attempts_ = "attempts";
    public static final int    _compress = 1232234516;
    public static final String _compress_ = "compress";
    public static final int    _packets = 384560432;
    public static final String _packets_ = "packets";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _mac = 474706838;
    public static final String _mac_ = "mac";
    public static final int    _dropped = 1815365056;
    public static final String _dropped_ = "dropped";
    public static final int    _errors = 1226221644;
    public static final String _errors_ = "errors";
    public static final int    _facility = 419851720;
    public static final String _facility_ = "facility";
    public static final int    _requestkey = 686156613;
    public static final String _requestkey_ = "requestkey";
    public static final int    _mask = 1167181041;
    public static final String _mask_ = "mask";
    public static final int    _peer = 1450174230;
    public static final String _peer_ = "peer";
    public static final int    _metric = 235154778;
    public static final String _metric_ = "metric";
    public static final int    _bytes = 1113108825;
    public static final String _bytes_ = "bytes";
    public static final int    _unit = 1638458042;
    public static final String _unit_ = "unit";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _level = 2112619197;
    public static final String _level_ = "level";
    public static final int    _archive_log = 1822308111;
    public static final String _archive_log_ = "archive-log";
    public static final int    _offset = 1966490361;
    public static final String _offset_ = "offset";
    public static final int    _comparison = 1181373760;
    public static final String _comparison_ = "comparison";
    public static final int    _broadcast = 1767430821;
    public static final String _broadcast_ = "broadcast";
    public static final int    _inet = 1716066537;
    public static final String _inet_ = "inet";
    public static final int    _arp = 2115159070;
    public static final String _arp_ = "arp";
    public static final int    _timeout = 614210192;
    public static final String _timeout_ = "timeout";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _routes = 278551890;
    public static final String _routes_ = "routes";
    public static final int    _domain = 2003714718;
    public static final String _domain_ = "domain";
    public static final int    _archive_path = 1927359332;
    public static final String _archive_path_ = "archive-path";
    public static final int    _inet6 = 1214809591;
    public static final String _inet6_ = "inet6";
    public static final int    _link = 481374722;
    public static final String _link_ = "link";
    public static final int    _c1 = 926807367;
    public static final String _c1_ = "c1";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _sys = 1280841638;
    public static final String _sys_ = "sys";
    public static final int    _family = 825379649;
    public static final String _family_ = "family";
    public static final int    _vlan_id = 1443431623;
    public static final String _vlan_id_ = "vlan-id";
    public static final int    _flag = 2035937176;
    public static final String _flag_ = "flag";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _controlkey = 1751774476;
    public static final String _controlkey_ = "controlkey";
    public static final int    _stratum = 1847827110;
    public static final String _stratum_ = "stratum";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _search = 472086744;
    public static final String _search_ = "search";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _collisions = 71575584;
    public static final String _collisions_ = "collisions";
    public static final int    _server = 163548884;
    public static final String _server_ = "server";
    public static final int    _delay = 200515694;
    public static final String _delay_ = "delay";
    public static final int    _reach = 50917064;
    public static final String _reach_ = "reach";
    public static final int    _options = 268171404;
    public static final String _options_ = "options";
    public static final int    _selector = 372182622;
    public static final String _selector_ = "selector";
    public static final int    _negate = 724559905;
    public static final String _negate_ = "negate";
    public static final int    _c2 = 365677982;
    public static final String _c2_ = "c2";
    public static final int    _local_clock = 988804996;
    public static final String _local_clock_ = "local-clock";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
